# Generated by Django 5.1.1 on 2025-01-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_search_vector_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="store_produ_search__ad07e0_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="search_vector",
        ),
    ]
