# Generated by Django 5.1.1 on 2025-01-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_reviewrating_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrating",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
