# Generated by Django 5.1.1 on 2025-01-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_reviewrating_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewrating",
            name="subject",
        ),
    ]
